[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Yifan Wu", email = "tyivanwu@gmail.com"},
]
dependencies = [
    "tensorflow-macos>=2.10.0",
    "tensorflow-metal>=0.6.0",
    "jupyterlab>=3.5.0",
    "black>=22.10.0",
    "matplotlib>=3.6.2",
    "jupyterlab-code-formatter>=1.5.3",
    "isort>=5.10.1",
    "torch>=1.13.0",
    "torchvision>=0.14.0",
    "torchaudio>=0.13.0",
    "torchinfo>=1.7.1",
]
requires-python = ">=3.9"
license = {text = "MIT"}

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"

[tool]
[tool.pdm]
