#!/bin/sh
# This file is autogenerated - DO NOT EDIT!
set -euo pipefail
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="${BASE_DIR}/../.."
(
cd ${REPO_DIR}
helm uninstall --namespace milvus my-milvus
helm uninstall --namespace pgvector my-pgvector
kubectl delete namespace milvus
kubectl delete namespace pgvector
)
